# Generated by Django 5.2.8 on 2025-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_role_farm_userprofile_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Agriculteur propriétaire'), ('TECH', 'Employé agricole')], default='TECH', max_length=10, verbose_name='Rôle'),
        ),
    ]
