# Generated by Django 5.2.8 on 2025-11-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='farm',
        ),
    ]
