# Generated by Django 5.2.8 on 2025-11-11 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0002_remove_culture_farm'),
        ('users', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='users.farm'),
        ),
    ]
