# Generated by Django 5.2.8 on 2025-11-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0003_culture_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='culture',
            name='pin_surface',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
