# Generated by Django 5.2.8 on 2025-11-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0004_cultureproduit_culture_pin_surface'),
        ('produits', '0001_initial'),
        ('sols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='sols.analysesol'),
        ),
        migrations.AddField(
            model_name='cultureproduit',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.culture'),
        ),
        migrations.AddField(
            model_name='cultureproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit'),
        ),
        migrations.AddField(
            model_name='culture',
            name='produits_utilises',
            field=models.ManyToManyField(related_name='cultures', through='cultures.CultureProduit', to='produits.produit'),
        ),
    ]
