# Generated by Django 5.2.7 on 2025-11-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0005_culture_sol_cultureproduit_culture_and_more'),
        ('users', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.culture')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.farm')),
            ],
            options={
                'unique_together': {('farm', 'culture', 'date')},
            },
        ),
    ]
