# Generated by Django 5.2.8 on 2025-11-06 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('idSerre', models.AutoField(primary_key=True, serialize=False)),
                ('nomSerre', models.CharField(default='Serre Principale', max_length=100, verbose_name='Nom de la serre')),
                ('nomCulture', models.CharField(max_length=100, verbose_name='Nom de la culture')),
                ('variete', models.CharField(max_length=100, verbose_name='Variété')),
                ('nombrePlantes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de plantes')),
                ('dateSemis', models.DateField(verbose_name='Date de semis')),
                ('dateRecoltePrevue', models.DateField(verbose_name='Date de récolte prévue')),
                ('etat', models.CharField(choices=[('Semée', 'Semée'), ('Croissance', 'Croissance'), ('Floraison', 'Floraison'), ('Maturité', 'Maturité'), ('Récoltée', 'Récoltée'), ('Abîmée', 'Abîmée')], max_length=20, verbose_name='État actuel')),
                ('datesIrrigation', models.TextField(blank=True, verbose_name="Dates d'irrigation (une date par ligne)")),
                ('frequenceArrosage', models.CharField(blank=True, max_length=50, verbose_name='Fréquence d’arrosage')),
                ('dateDerniereMiseAJour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
        ),
    ]
