# Generated by Django 5.2.7 on 2025-11-05 17:02

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('legume', 'Légume'), ('fruit', 'Fruit'), ('cereale', 'Céréale'), ('aromatique', 'Plante Aromatique'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('surface_m2', models.DecimalField(decimal_places=2, help_text='Surface en m²', max_digits=10)),
                ('date_semis', models.DateField()),
                ('date_recolte_prevue', models.DateField(blank=True, null=True)),
                ('besoin_base_l_j', models.DecimalField(decimal_places=2, default=0, help_text='Besoin en eau (litres/jour)', max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to=backoffice.models.upload_culture_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
