# Generated by Django 5.2.7 on 2025-11-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=200)),
                ('type_produit', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
