# Generated by Django 5.2.7 on 2025-11-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='date_recolte_prevue',
            field=models.DateField(),
        ),
    ]
