# Generated by Django 5.2.8 on 2025-11-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plantations/', verbose_name='Image de la plantation'),
        ),
    ]
