# Generated by Django 5.2.8 on 2025-11-06 14:16

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_plantation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backoffice.models.upload_culture_image, verbose_name='Image de la plantation'),
        ),
    ]
