# Generated by Django 5.2.7 on 2025-11-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(max_length=50),
        ),
    ]
