# Generated by Django 5.2.7 on 2025-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_alter_produit_description_alter_produit_nom_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite_stock',
            field=models.CharField(max_length=50),
        ),
    ]
