# Generated by Django 5.2.8 on 2025-11-06 15:42

import backoffice.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_alter_plantation_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantation',
            options={'ordering': ['-dateDerniereMiseAJour'], 'verbose_name': 'Plantation', 'verbose_name_plural': 'Plantations'},
        ),
        migrations.AlterField(
            model_name='plantation',
            name='dateRecoltePrevue',
            field=models.DateField(help_text='Date estimée de la récolte', verbose_name='Date de récolte prévue'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='dateSemis',
            field=models.DateField(help_text='Date à laquelle les graines ont été semées', verbose_name='Date de semis'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='datesIrrigation',
            field=models.TextField(blank=True, help_text='Entrez une date par ligne au format JJ/MM/AAAA', verbose_name="Dates d'irrigation (une date par ligne)"),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='etat',
            field=models.CharField(choices=[('Semée', 'Semée'), ('Croissance', 'Croissance'), ('Floraison', 'Floraison'), ('Maturité', 'Maturité'), ('Récoltée', 'Récoltée'), ('Abîmée', 'Abîmée')], default='Semée', max_length=20, verbose_name='État actuel'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='frequenceArrosage',
            field=models.CharField(blank=True, help_text='Ex: Tous les 2 jours, 3 fois par semaine, etc.', max_length=50, validators=[django.core.validators.RegexValidator(message='La fréquence ne peut contenir que des lettres, chiffres, espaces et tirets', regex='^[a-zA-Z0-9\\s\\-]+$')], verbose_name="Fréquence d'arrosage"),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='image',
            field=models.ImageField(blank=True, help_text='Format supporté: JPG, PNG, GIF. Taille max: 5MB', null=True, upload_to=backoffice.models.upload_culture_image, verbose_name='Image de la plantation'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='nomCulture',
            field=models.CharField(help_text='Nom de la culture (ex: Tomate, Laitue, Carotte)', max_length=100, validators=[django.core.validators.RegexValidator(message='Le nom ne peut contenir que des lettres, espaces et tirets', regex='^[a-zA-ZÀ-ÿ\\s\\-]+$')], verbose_name='Nom de la culture'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='nomSerre',
            field=models.CharField(default='Serre Principale', help_text='Nom de la serre (lettres, espaces et tirets uniquement)', max_length=100, validators=[django.core.validators.RegexValidator(message='Le nom ne peut contenir que des lettres, espaces et tirets', regex='^[a-zA-ZÀ-ÿ\\s\\-]+$')], verbose_name='Nom de la serre'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='nombrePlantes',
            field=models.PositiveIntegerField(help_text='Nombre de plantes (entre 1 et 10 000)', validators=[django.core.validators.MinValueValidator(1, message='Le nombre de plantes doit être au moins 1'), django.core.validators.MaxValueValidator(10000, message='Le nombre de plantes ne peut pas dépasser 10 000')], verbose_name='Nombre de plantes'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='variete',
            field=models.CharField(help_text='Variété spécifique (ex: Cerise, Romaine, Nantaise)', max_length=100, validators=[django.core.validators.RegexValidator(message='Le nom ne peut contenir que des lettres, espaces et tirets', regex='^[a-zA-ZÀ-ÿ\\s\\-]+$')], verbose_name='Variété'),
        ),
    ]
