# Generated by Django 5.2.8 on 2025-11-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_alter_plantation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='heureArrosage',
            field=models.TimeField(blank=True, default='08:00', help_text="Heure fixe pour l'arrosage (ex: 08:00)", null=True, verbose_name="Heure d'arrosage"),
        ),
    ]
