# Generated by Django 5.2.7 on 2025-11-05 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_alter_produit_quantite_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'La description doit contenir au moins 10 caractères.')]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom_produit',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Le nom du produit doit contenir au moins 2 caractères.')]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_stock',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="La quantité doit être un nombre suivi éventuellement d'une unité (ex: 500 kg, 5 litres).", regex='^[0-9]+(\\s?(kg|litres|pièces|unité|mL|g))?$')]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Le type de produit ne doit contenir que des lettres et des espaces.', regex='^[A-Za-zÀ-ÿ\\s-]+$')]),
        ),
    ]
