# Generated by Django 5.2.7 on 2025-11-05 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_alter_produit_description_alter_produit_nom_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite_stock',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='La quantité ne doit contenir que des lettres, chiffres et espaces.', regex='^[A-Za-z0-9\\s]+$')]),
        ),
    ]
