# Generated by Django 5.2.7 on 2025-11-06 22:10

import backoffice.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_alter_produit_quantite_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('legume', 'Légume'), ('fruit', 'Fruit'), ('cereale', 'Céréale'), ('aromatique', 'Plante Aromatique'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('surface_m2', models.DecimalField(decimal_places=2, help_text='Surface en m²', max_digits=10)),
                ('date_semis', models.DateField()),
                ('date_recolte_prevue', models.DateField()),
                ('besoin_base_l_j', models.DecimalField(decimal_places=2, default=0, help_text='Besoin en eau (litres/jour)', max_digits=8)),
                ('image', models.ImageField(upload_to=backoffice.models.upload_culture_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(upload_to='produits/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_stock',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="La quantité doit commencer par un nombre, suivi éventuellement d'unités (ex: '25 kg', '10 L').", regex='^[0-9]+[A-Za-zÀ-ÿ\\s]*$')]),
        ),
    ]
