# Generated by Django 5.2.7 on 2025-11-06 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_culture_alter_produit_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_utilisee', models.PositiveIntegerField(default=0)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.culture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.produit')),
            ],
        ),
        migrations.AddField(
            model_name='culture',
            name='produits_utilises',
            field=models.ManyToManyField(related_name='cultures', through='backoffice.CultureProduit', to='backoffice.produit'),
        ),
    ]
