# Generated by Django 5.2.8 on 2025-11-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0008_cultureproduit_culture_produits_utilises"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyseSol",
            fields=[
                ("id_analyse", models.AutoField(primary_key=True, serialize=False)),
                ("date_analyse", models.DateField(auto_now_add=True)),
                (
                    "pin_surface",
                    models.CharField(max_length=50, verbose_name="PIN Surface"),
                ),
                (
                    "surface",
                    models.DecimalField(
                        decimal_places=2, help_text="Surface en hectares", max_digits=10
                    ),
                ),
                (
                    "total_region",
                    models.CharField(max_length=100, verbose_name="Région totale"),
                ),
                (
                    "bundles_composition",
                    models.TextField(verbose_name="Composition des bundles"),
                ),
                (
                    "qualite_sol",
                    models.CharField(
                        choices=[
                            ("excellente", "Excellente"),
                            ("bonne", "Bonne"),
                            ("moyenne", "Moyenne"),
                            ("mauvaise", "Mauvaise"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ph", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "azote",
                    models.DecimalField(
                        decimal_places=2, help_text="mg/kg", max_digits=5
                    ),
                ),
                (
                    "phosphore",
                    models.DecimalField(
                        decimal_places=2, help_text="mg/kg", max_digits=5
                    ),
                ),
                (
                    "potassium",
                    models.DecimalField(
                        decimal_places=2, help_text="mg/kg", max_digits=5
                    ),
                ),
                ("localisation", models.CharField(max_length=200)),
                ("recommandations", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Analyse de sol",
                "verbose_name_plural": "Analyses de sol",
                "ordering": ["-date_analyse"],
            },
        ),
    ]
