# Generated by Django 5.2.8 on 2025-11-08 13:44

import backoffice.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_analysesol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('idSerre', models.AutoField(primary_key=True, serialize=False)),
                ('nomSerre', models.CharField(default='Serre Principale', help_text='Nom de la serre (lettres, espaces et tirets uniquement)', max_length=100, validators=[django.core.validators.RegexValidator(message='Le nom ne peut contenir que des lettres, espaces et tirets', regex='^[a-zA-ZÀ-ÿ\\s\\-]+$')], verbose_name='Nom de la serre')),
                ('nomCulture', models.CharField(help_text='Nom de la culture (ex: Tomate, Laitue, Carotte)', max_length=100, validators=[django.core.validators.RegexValidator(message='Le nom ne peut contenir que des lettres, espaces et tirets', regex='^[a-zA-ZÀ-ÿ\\s\\-]+$')], verbose_name='Nom de la culture')),
                ('variete', models.CharField(help_text='Variété spécifique (ex: Cerise, Romaine, Nantaise)', max_length=100, validators=[django.core.validators.RegexValidator(message='Le nom ne peut contenir que des lettres, espaces et tirets', regex='^[a-zA-ZÀ-ÿ\\s\\-]+$')], verbose_name='Variété')),
                ('nombrePlantes', models.PositiveIntegerField(help_text='Nombre de plantes (entre 1 et 10 000)', validators=[django.core.validators.MinValueValidator(1, message='Le nombre de plantes doit être au moins 1'), django.core.validators.MaxValueValidator(10000, message='Le nombre de plantes ne peut pas dépasser 10 000')], verbose_name='Nombre de plantes')),
                ('dateSemis', models.DateField(help_text='Date à laquelle les graines ont été semées', verbose_name='Date de semis')),
                ('dateRecoltePrevue', models.DateField(help_text='Date estimée de la récolte', verbose_name='Date de récolte prévue')),
                ('etat', models.CharField(choices=[('Semée', 'Semée'), ('Croissance', 'Croissance'), ('Floraison', 'Floraison'), ('Maturité', 'Maturité'), ('Récoltée', 'Récoltée'), ('Abîmée', 'Abîmée')], default='Semée', max_length=20, verbose_name='État actuel')),
                ('datesIrrigation', models.TextField(blank=True, help_text='Entrez une date par ligne au format JJ/MM/AAAA', verbose_name="Dates d'irrigation (une date par ligne)")),
                ('frequenceArrosage', models.CharField(blank=True, help_text='Ex: Tous les 2 jours, 3 fois par semaine, etc.', max_length=50, validators=[django.core.validators.RegexValidator(message='La fréquence ne peut contenir que des lettres, chiffres, espaces et tirets', regex='^[a-zA-Z0-9\\s\\-]+$')], verbose_name="Fréquence d'arrosage")),
                ('heureArrosage', models.TimeField(blank=True, default='08:00', help_text="Heure fixe pour l'arrosage (ex: 08:00)", null=True, verbose_name="Heure d'arrosage")),
                ('dateDerniereMiseAJour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('image', models.ImageField(blank=True, help_text='Format supporté: JPG, PNG, GIF. Taille max: 5MB', null=True, upload_to=backoffice.models.upload_culture_image, verbose_name='Image de la plantation')),
            ],
            options={
                'verbose_name': 'Plantation',
                'verbose_name_plural': 'Plantations',
                'ordering': ['-dateDerniereMiseAJour'],
            },
        ),
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
    ]
