# Generated by Django 5.2.8 on 2025-11-08 15:53

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_plantation_alter_culture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysesol',
            name='type',
            field=models.CharField(choices=[('argileux', 'Argileux'), ('sableux', 'Sableux'), ('limoneux', 'Limoneux'), ('humifere', 'Humifère')], default='autre', max_length=20),
        ),
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
    ]
