# Generated by Django 5.2.8 on 2025-11-10 17:51

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_remove_analysesol_type_alter_analysesol_pin_surface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='pin_surface',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
    ]
