# Generated by Django 5.2.8 on 2025-11-10 19:43

import backoffice.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_alter_culture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantation',
            name='pin_surface',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='plantation',
            name='sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plantation', to='backoffice.analysesol'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
    ]
