# Generated by Django 5.2.8 on 2025-11-10 20:25

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_plantation_pin_surface_plantation_sol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysesol',
            name='pin_surface',
        ),
        migrations.RemoveField(
            model_name='plantation',
            name='pin_surface',
        ),
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
    ]
