# Generated by Django 5.2.8 on 2025-11-10 20:27

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_remove_analysesol_pin_surface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
    ]
