# Generated by Django 5.2 on 2025-11-10 21:57

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_analysesol_pin_surface_alter_culture_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationMeteo',
            fields=[
                ('id_station', models.CharField(editable=False, help_text='Format: 0001, 0002, etc. Généré automatiquement', max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='ID Station')),
                ('nom_station', models.CharField(max_length=30, verbose_name='Nom de la station')),
                ('id_sol', models.CharField(blank=True, max_length=50, verbose_name='ID Capteur Sol')),
                ('id_capteur_pluie', models.CharField(blank=True, max_length=50, verbose_name='ID Capteur Pluie')),
                ('id_capteur_luminosite_humidite', models.CharField(blank=True, max_length=50, verbose_name='ID Capteur Luminosité/Humidité')),
                ('id_capteur_vent', models.CharField(blank=True, max_length=50, verbose_name='ID Capteur Vent')),
                ('date_installation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'installation")),
                ('emplacement', models.CharField(blank=True, max_length=100, verbose_name='Emplacement')),
                ('actif', models.BooleanField(default=True, verbose_name='Station active')),
            ],
            options={
                'verbose_name': 'Station Météo',
                'verbose_name_plural': 'Stations Météo',
                'ordering': ['id_station'],
            },
        ),
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
    ]
