# Generated by Django 5.2 on 2025-11-10 22:03

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_stationmeteo_alter_culture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
    ]
