# Generated by Django 5.2 on 2025-11-10 23:51

import backoffice.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0025_alter_culture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
        migrations.AlterField(
            model_name='culture',
            name='sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultures', to='backoffice.analysesol'),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Plantation', to='backoffice.analysesol'),
        ),
        migrations.AlterField(
            model_name='stationmeteo',
            name='sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StationMeteo', to='backoffice.analysesol'),
        ),
    ]
