# Generated by Django 5.2 on 2025-11-10 23:58

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0026_alter_culture_image_alter_culture_sol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(upload_to=backoffice.models.upload_culture_image),
        ),
    ]
