# Generated by Django 5.2.6 on 2025-11-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysesol",
            name="photo_sol",
        ),
    ]
