# Generated by Django 5.2.8 on 2025-11-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseSol',
            fields=[
                ('id_analyse', models.AutoField(primary_key=True, serialize=False)),
                ('pin_surface', models.CharField(choices=[('argileux', 'Argileux'), ('sableux', 'Sableux'), ('limoneux', 'Limoneux'), ('humifere', 'Humifère')], default='argileux', max_length=20)),
                ('date_analyse', models.DateField(auto_now_add=True)),
                ('surface', models.DecimalField(decimal_places=2, help_text='Surface en hectares', max_digits=10)),
                ('total_region', models.CharField(max_length=100, verbose_name='Région totale')),
                ('bundles_composition', models.TextField(verbose_name='Composition des bundles')),
                ('qualite_sol', models.CharField(choices=[('excellente', 'Excellente'), ('bonne', 'Bonne'), ('moyenne', 'Moyenne'), ('mauvaise', 'Mauvaise')], max_length=50)),
                ('ph', models.DecimalField(decimal_places=1, max_digits=3)),
                ('azote', models.DecimalField(decimal_places=2, help_text='mg/kg', max_digits=5)),
                ('phosphore', models.DecimalField(decimal_places=2, help_text='mg/kg', max_digits=5)),
                ('potassium', models.DecimalField(decimal_places=2, help_text='mg/kg', max_digits=5)),
                ('localisation', models.CharField(max_length=200)),
                ('recommandations', models.TextField(blank=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses_sol', to='users.farm')),
            ],
            options={
                'verbose_name': 'Analyse de sol',
                'verbose_name_plural': 'Analyses de sol',
                'ordering': ['-date_analyse'],
            },
        ),
    ]
