# Generated by Django 5.2.9 on 2025-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sols", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysesol",
            name="azote",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="analysesol",
            name="bundles_composition",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="analysesol",
            name="phosphore",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="analysesol",
            name="potassium",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="analysesol",
            name="qualite_sol",
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="analysesol",
            name="surface",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="analysesol",
            name="total_region",
            field=models.CharField(max_length=100),
        ),
    ]
