# Generated by Django 5.2.8 on 2025-11-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sols', '0001_initial'),
        ('users', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationMeteo',
            fields=[
                ('id_station', models.CharField(editable=False, help_text='Format: 0001, 0002, etc. Généré automatiquement', max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='ID Station')),
                ('nom_station', models.CharField(max_length=30, verbose_name='Nom de la station')),
                ('id_sol', models.CharField(blank=True, max_length=50, verbose_name='ID Capteur Sol')),
                ('id_capteur_pluie', models.CharField(blank=True, max_length=50, verbose_name='ID Capteur Pluie')),
                ('id_capteur_luminosite_humidite', models.CharField(blank=True, max_length=50, verbose_name='ID Capteur Luminosité/Humidité')),
                ('id_capteur_vent', models.CharField(blank=True, max_length=50, verbose_name='ID Capteur Vent')),
                ('date_installation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'installation")),
                ('emplacement', models.CharField(blank=True, max_length=100, verbose_name='Emplacement')),
                ('actif', models.BooleanField(default=True, verbose_name='Station active')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations_meteo', to='users.farm')),
                ('sol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stations_meteo', to='sols.analysesol')),
            ],
            options={
                'verbose_name': 'Station Météo',
                'verbose_name_plural': 'Stations Météo',
                'ordering': ['id_station'],
            },
        ),
    ]
