# Generated by Django 5.2.8 on 2025-11-11 23:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Le nom du produit doit contenir au moins 2 caractères.')])),
                ('type_produit', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Le type de produit ne doit contenir que des lettres et des espaces.', regex='^[A-Za-zÀ-ÿ\\s-]+$')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'La description doit contenir au moins 10 caractères.')])),
                ('quantite_stock', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="La quantité doit commencer par un nombre, suivi éventuellement d'unités (ex: '25 kg', '10 L').", regex='^[0-9]+[A-Za-zÀ-ÿ\\s]*$')])),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='produits/')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='users.farm')),
            ],
        ),
    ]
